### ISSUE TITLE
v9

### ISSUE THREAD

**Issue by brunocalado** [eHanus/foundryvtt-wicked-ones#28]
Hi.

Please remove the foundry vtt warning.

Replace "compatibleCoreVersion":"9.xxx" by "compatibleCoreVersion":"9".

Docs: https://gitlab.com/foundrynet/foundryvtt/-/issues/5635

**Comment by eHanus** [comment]
Sorry for taking this long to notice the issue. Did so in the final v9 release some weeks ago.
