### ISSUE TITLE
Update to Foundry v12?

### ISSUE THREAD

**Issue by JKarneeb** [eHanus/foundryvtt-wicked-ones#41]
Wondering if you intend to update this system to V12 for Foundry?  In V12, none of the character attributes are directly rollable from sheets or macros seemingly due to a change in the api that removed the game.system.model shorthand.

**Comment by eHanus** [comment]
Currently not working on the module. If you want to fix the system for v12 feel free to do the update and send me a pull request. Didn't expect v12 to break the system but there may have been a change I did not have on my radar back when v12 was announced.

**Comment by eHanus** [comment]
Version 1.1.3 is out now and adds FVTT 12 support.
